
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "leftPLUSMINUSleftMULTIPLYDIVIDEDIVIDE EQUALS FLOAT INT MINUS MULTIPLY NAME PLUS STRING agejdan azayez ilem taggayt urkid\n    code : azayez taggayt NAME '{' main '}'\n    \n    main : azayez urkid ilem agejdan '(' ')' '{' statements '}'\n    \n    statements : statements statement\n                | empty\n    \n    statement   : var_assign\n                | empty\n    \n    var_assign : NAME EQUALS expression\n    \n    expression :  expression MULTIPLY expression\n                | expression DIVIDE expression\n                | expression MINUS expression\n                | expression PLUS expression\n    \n    expression : INT \n                | FLOAT\n    \n    expression : STRING\n    \n    expression : NAME\n    \n    empty :\n    "
    
_lr_action_items = {'azayez':([0,5,],[2,6,]),'$end':([1,9,],[0,-1,]),'taggayt':([2,],[3,]),'NAME':([3,14,15,16,18,19,20,22,23,24,25,26,27,28,29,30,31,32,33,34,35,],[4,-16,21,-4,-3,-5,-6,23,-15,-7,-12,-13,-14,23,23,23,23,-8,-9,-10,-11,]),'{':([4,13,],[5,14,]),'urkid':([6,],[8,]),'}':([7,14,15,16,17,18,19,20,23,24,25,26,27,32,33,34,35,],[9,-16,17,-4,-2,-3,-5,-6,-15,-7,-12,-13,-14,-8,-9,-10,-11,]),'ilem':([8,],[10,]),'agejdan':([10,],[11,]),'(':([11,],[12,]),')':([12,],[13,]),'EQUALS':([21,],[22,]),'INT':([22,28,29,30,31,],[25,25,25,25,25,]),'FLOAT':([22,28,29,30,31,],[26,26,26,26,26,]),'STRING':([22,28,29,30,31,],[27,27,27,27,27,]),'MULTIPLY':([23,24,25,26,27,32,33,34,35,],[-15,28,-12,-13,-14,-8,-9,28,28,]),'DIVIDE':([23,24,25,26,27,32,33,34,35,],[-15,29,-12,-13,-14,-8,-9,29,29,]),'MINUS':([23,24,25,26,27,32,33,34,35,],[-15,30,-12,-13,-14,-8,-9,-10,-11,]),'PLUS':([23,24,25,26,27,32,33,34,35,],[-15,31,-12,-13,-14,-8,-9,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'code':([0,],[1,]),'main':([5,],[7,]),'statements':([14,],[15,]),'empty':([14,15,],[16,20,]),'statement':([15,],[18,]),'var_assign':([15,],[19,]),'expression':([22,28,29,30,31,],[24,32,33,34,35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> code","S'",1,None,None,None),
  ('code -> azayez taggayt NAME { main }','code',6,'p_code','TamazightLexerParser.py',97),
  ('main -> azayez urkid ilem agejdan ( ) { statements }','main',9,'p_main','TamazightLexerParser.py',102),
  ('statements -> statements statement','statements',2,'p_statements','TamazightLexerParser.py',107),
  ('statements -> empty','statements',1,'p_statements','TamazightLexerParser.py',108),
  ('statement -> var_assign','statement',1,'p_statement','TamazightLexerParser.py',113),
  ('statement -> empty','statement',1,'p_statement','TamazightLexerParser.py',114),
  ('var_assign -> NAME EQUALS expression','var_assign',3,'p_varAssign','TamazightLexerParser.py',120),
  ('expression -> expression MULTIPLY expression','expression',3,'p_expression','TamazightLexerParser.py',127),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression','TamazightLexerParser.py',128),
  ('expression -> expression MINUS expression','expression',3,'p_expression','TamazightLexerParser.py',129),
  ('expression -> expression PLUS expression','expression',3,'p_expression','TamazightLexerParser.py',130),
  ('expression -> INT','expression',1,'p_expression_int_float','TamazightLexerParser.py',136),
  ('expression -> FLOAT','expression',1,'p_expression_int_float','TamazightLexerParser.py',137),
  ('expression -> STRING','expression',1,'p_expression_string','TamazightLexerParser.py',143),
  ('expression -> NAME','expression',1,'p_expression_var','TamazightLexerParser.py',149),
  ('empty -> <empty>','empty',0,'p_empty','TamazightLexerParser.py',155),
]
